name: Java CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest  # macOS environment

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Specify Temurin as the distribution


    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test