name: second feature test

on:
  workflow_dispatch:
    inputs:
        test-tag:
            description: 'smoke'
            required: false
            type: string

jobs:
  build:
    runs-on: macos-latest  # macOS environment

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # Specify Temurin as the distribution


    - name: Build with Maven
      run: mvn clean install

    # - name: Run tests
    #   run: mvn test
    - name: Run tests with tag
      run: |
        if [ -z "${{ github.event.inputs.test-tag }}" ]; then
          mvn test  # Run all tests if no tag is provided
        else
          mvn test -Dtest=${{ github.event.inputs.test-tag }}  # Run specific test by tag
        fi